package acme

import (
	"strconv"
	"sync"
	"testing"

	"github.com/coredns/coredns/plugin"
	"github.com/miekg/dns"
	"github.com/prometheus/client_golang/prometheus"
)

var (
	dns01ResponseCount *prometheus.CounterVec
	peerProbeCount     *prometheus.CounterVec
	metricsOnce        sync.Once
)

// initMetrics initializes and registers ACME metrics with appropriate registry.
// Uses sync.Once to ensure single initialization across parallel tests.
// The first test to call this determines the registry type, which is fine since
// each test gets its own TestInfrastructure with isolated CoreDNS instance.
func initMetrics() {
	metricsOnce.Do(func() {
		var registry prometheus.Registerer = prometheus.DefaultRegisterer

		if testing.Testing() {
			// Use isolated registry in tests to avoid metric collisions
			registry = prometheus.NewRegistry()
		}

		dns01ResponseCount = prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: plugin.Namespace,
			Subsystem: "forge_" + pluginName,
			Name:      "dns01_responses_total",
			Help:      "The count of DNS-01 TXT responses generated by p2p-forge plugin.",
		}, []string{"type"})

		peerProbeCount = prometheus.NewCounterVec(prometheus.CounterOpts{
			Namespace: plugin.Namespace,
			Subsystem: "forge_" + pluginName,
			Name:      "libp2p_probe_total",
			Help:      "The count of libp2p probes performed before accepting registration by p2p-forge plugin.",
		}, []string{"result", "agent"})

		// Register with appropriate registry
		registry.MustRegister(dns01ResponseCount, peerProbeCount)
	})
}

// recordDNS01Response records a DNS-01 response metric
func recordDNS01Response(responseType string) {
	if dns01ResponseCount != nil {
		dns01ResponseCount.WithLabelValues(responseType).Add(1)
	}
}

// recordPeerProbe records a peer probe metric
func recordPeerProbe(result, agent string) {
	if peerProbeCount != nil {
		peerProbeCount.WithLabelValues(result, agent).Add(1)
	}
}

func dnsToString(dnsType uint16) string {
	if str, ok := dns.TypeToString[dnsType]; ok {
		return str
	}
	return strconv.Itoa(int(dnsType))
}
